### ISSUE TITLE
document making

### ISSUE THREAD

**Issue by Worldeditory** [SKKU-VRAR/guide#2]
문서 작성이 필요함, 나 준휘형 준원이형 원모형 4명이서 작성하면 될듯

**Comment by DropFL** [comment]
어떤 문서들이 필요한지 목록 작성 부탁드립니다.

**Comment by Worldeditory** [comment]
1. 리눅스 서버
2. 나스 서버
3. 장비 사용법
혹시 추가할것 있는분은 추가바람
